categories:
  - Electronics:
      - Mobile Phones & Accessories
      - Computers & Accessories
      - Audio & Video Equipment
      - Cameras & Photography
      - Gaming & Consoles
      - Smart Home Devices
  - Clothing & Accessories:
      - Men's Clothing
      - Women's Clothing
      - Children's Clothing
      - Footwear
      - Bags & Luggage
      - Jewelry & Watches
      - Eyewear
  - Home & Kitchen:
      - Kitchen Appliances
      - Home Appliances
      - Cookware & Bakeware
      - Tableware
      - Storage & Organization
      - Home Decor & Furnishings
  - Health & Beauty:
      - Personal Care Appliances
      - Makeup & Cosmetics
      - Skincare
      - Hair Care
      - Fragrances
      - Health & Wellness Products
  - Sports & Outdoors:
      - Fitness Equipment
      - Camping & Hiking Gear
      - Cycling
      - Water Sports
      - Team Sports Equipment
      - Outdoor Recreation
  - Toys & Games:
      - Action Figures & Collectibles
      - Board Games & Puzzles
      - Building Sets & Blocks
      - Educational Toys
      - Electronic & Interactive Toys
      - Outdoor Play Equipment
  - Automotive:
      - Car Electronics & Accessories
      - Car Parts & Components
      - Motorcycle & ATV Parts
      - Tires & Wheels
      - Tools & Equipment
      - Exterior & Interior Accessories
  - Books, Music, & Movies:
      - Books & Ebooks
      - CDs & Vinyl Records
      - DVDs & Blu-ray Discs
      - Magazines & Newspapers
      - Musical Instruments
      - Digital Downloads
  - Office & Stationery:
      - Office Supplies
      - Office Electronics
      - School Supplies
      - Art Supplies
      - Paper Products
      - Office Furniture
  - Grocery & Gourmet Foods:
      - Beverages
      - Snacks & Sweets
      - Pantry Staples
      - Baking & Cooking Supplies
      - Organic & Healthy Foods
      - International Foods
