categories:
  Electronics:
    Mobile Phones & Accessories: [10, 2000]
    Computers & Accessories: [10, 5000]
    Audio & Video Equipment: [10, 10000]
    Cameras & Photography: [50, 10000]
    Gaming & Consoles: [50, 1000]
    Smart Home Devices: [20, 2000]
  Clothing & Accessories:
    Men's Clothing: [5, 2000]
    Women's Clothing: [5, 2000]
    Children's Clothing: [5, 500]
    Footwear: [10, 2000]
    Bags & Luggage: [10, 5000]
    Jewelry & Watches: [10, 50000]
    Eyewear: [10, 1000]
  Home & Kitchen:
    Kitchen Appliances: [10, 10000]
    Home Appliances: [50, 10000]
    Cookware & Bakeware: [5, 1000]
    Tableware: [5, 1000]
    Storage & Organization: [5, 500]
    Home Decor & Furnishings: [5, 5000]
  Health & Beauty:
    Personal Care Appliances: [10, 500]
    Makeup & Cosmetics: [5, 200]
    Skincare: [5, 500]
    Hair Care: [5, 500]
    Fragrances: [10, 500]
    Health & Wellness Products: [5, 1000]
  Sports & Outdoors:
    Fitness Equipment: [10, 10000]
    Camping & Hiking Gear: [5, 2000]
    Cycling: [10, 10000]
    Water Sports: [10, 5000]
    Team Sports Equipment: [10, 5000]
    Outdoor Recreation: [10, 10000]
  Toys & Games:
    Action Figures & Collectibles: [5, 1000]
    Board Games & Puzzles: [5, 500]
    Building Sets & Blocks: [5, 500]
    Educational Toys: [5, 500]
    Electronic & Interactive Toys: [10, 1000]
    Outdoor Play Equipment: [10, 5000]
  Automotive:
    Car Electronics & Accessories: [10, 2000]
    Car Parts & Components: [10, 10000]
    Motorcycle & ATV Parts: [10, 5000]
    Tires & Wheels: [50, 2000]
    Tools & Equipment: [10, 5000]
    Exterior & Interior Accessories: [5, 1000]
  Books, Music, & Movies:
    Books & Ebooks: [1, 500]
    CDs & Vinyl Records: [1, 200]
    DVDs & Blu-ray Discs: [5, 200]
  Office & Stationery:
    Office Supplies: [1, 100]
    Office Electronics: [20, 5000]
    School Supplies: [1, 200]
    Art Supplies: [1, 500]
    Paper Products: [1, 200]
    Office Furniture: [50, 5000]
  Grocery & Gourmet Foods:
    Beverages: [1, 100]
    Snacks & Sweets: [1, 100]
    Pantry Staples: [1, 200]
    Baking & Cooking Supplies: [1, 200]
    Organic & Healthy Foods: [1, 300]
    International Foods: [1, 300]
